
[Settings]
ID = "2ab5b2e5-5e79-4481-8b9d-59c7cd4c5509"

# Settings in the [build] context are global and are applied to all contexts unless otherwise overridden by more specific contexts.  

[build]
  # This is the directory to change to before starting a build.
  base    = "lotr-posts/"
  # NOTE: This is where we will look for package.json/.nvmrc/etc, not root.
  # This is the directory that you are publishing from (relative to root of your repo)
  publish = "lotr-posts/build/"
  # This will be your default build command
  command = "yarn build"